### ISSUE TITLE
Needs upgraded VCS library.

### ISSUE THREAD

**Issue by ferrants** [niedbalski/python-bugspots#2]
Saw the following error when running it after installing through pip:
```
$ bugspots --branch master --days 30 --limit 10
Traceback (most recent call last):
  File "/Users/mferrante/code/dxansible/bugspot_env/bin/bugspots", line 9, in <module>
    load_entry_point('bug-spots==0.2.4', 'console_scripts', 'bugspots')()
  File "/Users/mferrante/code/dxansible/bugspot_env/lib/python2.7/site-packages/bugspots/__init__.py", line 157, in main
    print_code_hotspots(options)
  File "/Users/mferrante/code/dxansible/bugspot_env/lib/python2.7/site-packages/bugspots/__init__.py", line 123, in print_code_hotspots
    for factor, filename in get_code_hotspots(options):
  File "/Users/mferrante/code/dxansible/bugspot_env/lib/python2.7/site-packages/bugspots/__init__.py", line 78, in get_code_hotspots
    commits = get_fix_commits(client, options.branch, options.days)
  File "/Users/mferrante/code/dxansible/bugspot_env/lib/python2.7/site-packages/bugspots/__init__.py", line 69, in get_fix_commits
    for change in changelogs(days_ago):
  File "/Users/mferrante/code/dxansible/bugspot_env/lib/python2.7/site-packages/bugspots/__init__.py", line 58, in changelogs
    changelogs = [change for change in client.get_changesets(client.repo)]
  File "/Users/mferrante/code/dxansible/bugspot_env/lib/python2.7/site-packages/vcs/cli.py", line 409, in get_changesets
    if not options['all']:
KeyError: 'all'
```

I upgraded the vcs install with:
```
$ pip install git+git://github.com/codeinn/vcs.git@master#vcs --upgrade
```

And it worked then

**Comment by niedbalski** [comment]
@ferrants  Funny, just a second after you opened this PR, the vcs package was upgraded (https://github.com/codeinn/vcs/pull/117)

**Comment by ferrants** [comment]
I don't think it's been upgraded yet, shows 0.4.0 on pypi https://pypi.python.org/pypi/vcs. Just trying to bring more visibility to your fix so I can use your bugspots script. Thanks, btw!

**Comment by sils1297** [comment]
yep, this still doesn't work

**Comment by niedbalski** [comment]
@ferrants @sils1297 The latest release 0.3 fixes this issue by using vcstools instead.

Thanks for opening this bug.
